static const FFCodecParser * const parser_list[] = {
    &ff_aac_parser,
    &ff_aac_latm_parser,
    &ff_ac3_parser,
    &ff_amr_parser,
    &ff_cook_parser,
    &ff_dca_parser,
    &ff_flac_parser,
    &ff_mlp_parser,
    &ff_mpegaudio_parser,
    &ff_opus_parser,
    &ff_sipr_parser,
    &ff_tak_parser,
    &ff_vorbis_parser,
    NULL };
