static const FFInputFormat * const demuxer_list[] = {
    &ff_aac_demuxer,
    &ff_ac3_demuxer,
    &ff_aiff_demuxer,
    &ff_amr_demuxer,
    &ff_ape_demuxer,
    &ff_asf_demuxer,
    &ff_au_demuxer,
    &ff_dsf_demuxer,
    &ff_dts_demuxer,
    &ff_dtshd_demuxer,
    &ff_flac_demuxer,
    &ff_m4v_demuxer,
    &ff_matroska_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_mpc_demuxer,
    &ff_mpc8_demuxer,
    &ff_ogg_demuxer,
    &ff_rm_demuxer,
    &ff_tak_demuxer,
    &ff_truehd_demuxer,
    &ff_tta_demuxer,
    &ff_wav_demuxer,
    &ff_wv_demuxer,
    NULL };
