# Automatically generated by configure - do not modify!
shared=
build_suffix=
prefix=/usr/local
libdir=${prefix}/lib
incdir=${prefix}/include
rpath=
source_path=/d/a/ffmpeg-config/ffmpeg-config/ffmpeg
LIBPREF=
LIBSUF=.lib
extralibs_avutil="user32.lib
bcrypt.lib"
extralibs_avcodec="ole32.lib
user32.lib"
extralibs_avformat=""
extralibs_avdevice=""
extralibs_avfilter=""
extralibs_swscale=""
extralibs_swresample=""
avdevice_deps="avformat avcodec swresample avutil"
avfilter_deps="avutil"
swscale_deps="avutil"
avformat_deps="avcodec swresample avutil"
avcodec_deps="swresample avutil"
swresample_deps="avutil"
avutil_deps=""
